### ISSUE TITLE
Build steps not working on Kubuntu 18.04

### ISSUE THREAD

**Issue by TomyLobo** [alvanieto/vbox-runner#4]
The steps from the "Build" section of the README.md don't work at all.
cmake complains about missing directories and if I mkdir them, it complains about a missing CMakeLists.txt.
I ended up just doing `cmake . && make && sudo make install`, which produced a working binary, but installed it to the wrong directory.
Where krunner expects it: /usr/lib/x86_64-linux-gnu/qt5/plugins
Where "make install" actually put it: /usr/local/lib/x86_64-linux-gnu/plugins

Anyway, still a great piece of software, once those build problems were resolved, no extra configuration was needed, it just worked out of the box :)

**Comment by alvanieto** [comment]
Thank you, fixed.
